### ISSUE TITLE
Migration branch - build failure

### ISSUE THREAD

**Issue by GretaBocedi** [RangeShifter/RangeShifter_batch#70]
@TheoPannetier  could you please check the migration branch? It compiles fine on my Visual Studio but not here.

**Comment by TheoPannetier** [comment]
Hey Greta, the [failed build output](https://github.com/RangeShifter/RangeShifter_batch/actions/runs/10268624816/job/28412059176) provides useful info:
> [ 89%] Building CXX object CMakeFiles/RangeShifter.dir/src/Main.cpp.o
/home/runner/work/RangeShifter_batch/RangeShifter_batch/src/Main.cpp: In function ‘int main(int, char**)’:
/home/runner/work/RangeShifter_batch/RangeShifter_batch/src/Main.cpp:239:36: error: ‘struct batchfiles’ has no member named ‘repSeasons’; did you mean ‘repseasons’?
  239 |                 dem.repSeasons = b.repSeasons;
      |                                    ^~~~~~~~~~
      |                                    repseasons

And indeed, I get the same error on my local using VS:
> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'repSeasons': is not a member of 'batchfiles'	C:\Users\s02tp3\github\rs_batch_dev\out\build\x64-Debug\rs_batch_dev	C:\Users\s02tp3\github\rs_batch_dev\src\Main.cpp	239	

So it seems that one is trying to call member "repSeasons" of the batchfiles structure, which does not exist. Indeed, the member is called "repseasons". I just pushed a commit fixing the case.
I'm not sure why your version works, maybe because you activated some macros?

**Comment by TheoPannetier** [comment]
Closing, the issue seems to have been solved :)
